apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-demo
  labels:
    app: nodejs-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-demo
  template:
    metadata:
      labels:
        app: nodejs-demo
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-inject-secret-database: "secret/database"
        vault.hashicorp.com/role: "mysql"
        vault.hashicorp.com/auth-path: "/auth/kubernetes"
        vault.hashicorp.com/agent-inject-template-database: |
          {{- with secret "secret/database" -}}
          export MYSQL_PASSWORD={{ .Data.data.password }}
          export MYSQL_USERNAME={{ .Data.data.username }}
          {{- end }}
    spec:
      serviceAccountName: mysql
      containers:
        - name: nodejs-demo
          image: nerdeveloper/nodejs-demo
          args:
            [ 'sh', '-c', 'source /vault/secrets/database && node server.js'  ]
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
