apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-demo
  labels:
    app: nodejs-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-demo
  template:
    metadata:
      labels:
        app: nodejs-demo
    spec:
      containers:
      - name: nodejs
        image: nerdeveloper/nodejs-demo
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
              path: /health
              port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
